# Use an official Golang runtime as a parent image
FROM golang:1.17-alpine3.13

# Set the working directory to /app
WORKDIR /app

# Copy the Go application source code to the container
ADD . /app

ENV SQL_URL=root:root@tcp(localhost:3306)/mysql

# Build the Go application
RUN go mod download
RUN go build -o test

CMD ["./test"]